# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'FLS' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FLS
	pod 'Parse'
	pod 'RxSwift',    '~> 3.0'
  pod 'RxCocoa',    '~> 3.0'
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # needed for debugging

    # Add any other subspecs you want to use in your project
  ]
  
  target 'FLSTests' do
    inherit! :search_paths
    # Pods for testing
	pod 'RxBlocking', '~> 3.0'
    	pod 'RxTest',     '~> 3.0'

  end

  target 'FLSUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
